# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sys1.0.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPalette, QPixmap, QBrush
from PyQt5.QtWidgets import QLabel

import model


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 850)
        MainWindow.setFixedSize(1200, 850)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("res/images/bg.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 0, 2, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 0, 3, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 1, 0, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout.addWidget(self.pushButton_5, 1, 2, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout.addWidget(self.lineEdit_3, 1, 3, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 2, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 2, 1, 2)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setText("")
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 3, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1274, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        self.statusbar.addPermanentWidget(QLabel('西北大学'), stretch=3)
        MainWindow.setStatusBar(self.statusbar)
        # 设置 方法函数引用
        self.model = model.Model()

        self.retranslateUi(MainWindow)
        self.pushButton.clicked.connect(self.selectFile)
        self.pushButton_2.clicked.connect(self.selectProcessFolder)
        self.pushButton_3.clicked.connect(self.predict)
        self.pushButton_5.clicked.connect(self.selectFolder)
        self.pushButton_4.clicked.connect(self.mulPredict)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        # 设置背景图片
        palette = QPalette()
        pix = QPixmap("res/images/mwin.png")

        pix = pix.scaled(MainWindow.width(), MainWindow.height())
        # pix = pix.scaled(w.width(),w.height())

        palette.setBrush(QPalette.Background, QBrush(pix))
        MainWindow.setPalette(palette)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "唐卡线图提取展示系统"))
        self.pushButton.setText(_translate("MainWindow", "选择文件"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "选择要提取的图片，除图片外不含中文！！！"))
        self.pushButton_2.setText(_translate("MainWindow", "选择文件夹"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "图片所在文件夹，除图片外不含中文！"))
        self.pushButton_3.setText(_translate("MainWindow", "提取线图"))
        self.pushButton_5.setText(_translate("MainWindow", "选择文件夹"))
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow", "图片保存文件夹，除图片外不含中文！"))
        self.pushButton_4.setText(_translate("MainWindow", "批量提取线图"))
    def selectFile(self):
        self.model.selectFile(self)

    def selectFolder(self):
        self.model.selectFolder(self)

    def predict(self):
        self.model.predict(self)

    def mulPredict(self):
        self.model.mulPredict(self)
    def selectProcessFolder(self):
        self.model.selectProcessFolder(self)
# if __name__ == '__main__':
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     MainWindow = QtWidgets.QMainWindow()  # 创建窗体对象
#     ui = Ui_MainWindow()  # 创建PyQt设计的窗体对象
#     ui.setupUi(MainWindow)
#     MainWindow.show()
#     sys.exit(app.exec_())